apiVersion: v1
kind: Service
metadata:
  name: stock-your-lot-ui
  labels:
    app: stock-your-lot-ui
spec:
  type: LoadBalancer
  selector:
    app: stock-your-lot-ui
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
